# -*- coding: utf-8 -*-
"""LIFE_EXPECTANCY_PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-rRo-1oEppggHbfIE75hoHYKc4Rid5yA

**PROJECT NAME:- LIFE_EXPECTANCY IN INDIA**

***PROJECT DESCRIPTION:- IT IS A BASIC DATA ANALYSIS PROJECT IN WHICH WE TRIED TO UNDERSTAND THE TREND OF THE FEATURES WHICH AFFECT THE LIFE EXPECTANCY OF PEOPLE LIVING IN INDIA.***
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

"""# READING OUR DATAFRAME."""

df=pd.read_csv('Life Expectancy Data.csv')
df

plt.figure(figsize=(10, 5),dpi=100)
plt.subplot(121)
df.Status.value_counts().plot(kind='bar')
plt.title('Count of Rows by Country Status')
plt.xlabel('Country Status')
plt.ylabel('Count of Rows')
plt.xticks(rotation=0)

#Creating a dataframe consisting of average life expecatncy of each country. 
new_df=df.groupby('Country').mean()
new_df.reset_index(inplace=True)
country_life=new_df[['Country','Life expectancy ']]
country_life

#plotting the above data using barplot
plt.figure(figsize=(30,10),dpi=200)
sns.barplot(country_life['Country'],country_life['Life expectancy '],palette='deep')
plt.title('COUNTRY WISE AVG LIFE EXPECTANCY',size=30)
plt.grid(color='grey',axis='y')
plt.xticks(rotation=90)
plt.tight_layout()

"""# WE WILL ANALYZE THE DATA OF INDIA TO SEE HOW OTHER FACTORS AFFECT THE LIFE EXPECTANCY IN INDIA."""

#Extracting the data of India from our original dataset.
India_data=df.loc[1188:1201]
India_data

"""WE WILL CHECK FOR THE NULL VALUES IN OUR DATASET."""

#Checking for null values in our extracted dataset.
India_data.isnull()

India_data.isnull().sum()

#Renaming the column :
India_data.rename(columns={'Hepatitis B':'HepB'},inplace=True)

India_data

#Replacing the null values with the mean value of that respective feature.
India_data.HepB=India_data.HepB.fillna(India_data.HepB.mean())

A=India_data

A

A1=A[['Country','Year','Life expectancy ','Adult Mortality','infant deaths']]

A1

"""#OUTLIER DETECTION:"""

sns.boxplot(A1['Life expectancy '])

sns.boxplot(A1['Adult Mortality'])

sns.boxplot(A1['infant deaths'])

A1.describe()

corr1=A1.corr()
corr1

#Plotting the above correlational matrix in heatmap
plt.figure(figsize=(12,6),dpi=100)
sns.heatmap(corr1,annot=True,square=True,linewidths=0.5)
plt.title('CORRELATION HEATMAP',size=20)

"""FROM ABOVE CORRELATIONAL MATRIX AND HEATMAP WE CAN SEE THAT INFANT DEATHS AND ADULT MORTALITY RATES ARE NEGATIVELY CORRELATED WITH LIFE EXPECATNCY."""

#Visualizing the trend of life expectancy of India through barplot
plt.figure(figsize=(14,6),dpi=100)

sns.barplot(A1['Year'],A1['Life expectancy '],palette='icefire')
plt.title('YEAR WISE LIFE EXPECTANCY IN INDIA',size=20)
plt.legend()
plt.grid(color='grey',axis='y')
plt.tight_layout()

#Visualizing the adult mortality trend in India between (2000-2013)
plt.figure(figsize=(14,6),dpi=100)

sns.barplot(A1['Year'],A1['Adult Mortality'],palette='vlag')
plt.grid(color='grey',axis='y')
plt.title('YEAR WISE ADULT MORTALITY RATE IN INDIA',size=20)
plt.tight_layout()

# Visualizing the trend of Infant deaths in India between(2000-2013)
plt.figure(figsize=(14,6),dpi=100)
sns.barplot(A1['Year'],A1['infant deaths'],palette='deep')
plt.title('YEAR WISE INFANT DEATHS PER 1000 POPULATION',size=20)
plt.grid(color='grey',axis='y')
plt.tight_layout()

"""LET'S SEE HOW OTHER FACTORS AFFECT THE LIFE EXPECTANCY.

"""

A

A.describe()

corr=A.corr()
corr

#Visulazing the above correlational matrix in heatmap.
plt.figure(figsize=(40,20),dpi=100)
sns.heatmap(corr,annot=True,square=True,linewidths=.5)
plt.title('CORRELATION HEATMAP',size=20)

"""NOW WE WILL SEE HOW THESE FEATURES WHICH AFFECT LIFE EXPECTANCY HAS INCREASED OR DECREASED IN THESE YEARS."""

A

"""SINCE POLIO AND HEPB IMMUNIZATION COVERAGE IS POSITIVELY CORRELATED WITH LIFE EXPECTANCY FEATURE SO WE WILL SEE HOW THESE FEATURES HAS INCREASED OR DECREASED IN THESE YEARS."""

# Visualizing the polio and Hepatitis B immunization coverage in India
plt.figure(figsize=(16,6),dpi=100)

plt.plot(A['Year'],A['Polio'],color='orange',label='POLIO IMMUNIZATION',marker='o')
plt.plot(A['Year'],A['HepB'],color='blue',label='HEPATITS B IMMUNIZATION',marker='o')

plt.grid(color='grey')
plt.legend()
plt.tight_layout()

"""SINCE MEASLES AND UNDER-FIVE-DEATHS ARE NEGATIVELY CORRELATED WITH THE LIFE EXPECTANCY FEATURE SO LET'S SEE HOW THESE FEATURES HAVE INCREASED OR DECREASED IN THESE YEARS."""

# plotting the trend of  No. of Measles cases occuring in India.
plt.figure(figsize=(16,6),dpi=100)
sns.barplot(A['Year'],A['Measles '],palette='bright')
plt.grid(color='grey',axis='y')
plt.tight_layout()
plt.title('NO. OF MEASLES CASES(YEAR WISE)',size=20)

"""LET'S SEE HOW THE UNDER-FIVE DEATHS HAS INCREASED OR DECREASED IN THESE YEARS THROUGH BARPLOT"""

plt.figure(figsize=(16,6),dpi=100)
sns.barplot(A['Year'],A['under-five deaths '])
plt.grid(color='grey',axis='y')
plt.tight_layout()
plt.title('UNDER-FIVE DEATHS',size=20)

"""SINCE DIPTHERIA IMMUNIZATION COVERAGE HAS A POSITIVE CORRELATION WITH LIFE EXPECTANCY, SO LET'S SEE HOW THIS IMMUNIZATION COVERAGE HAS INCREASED IN THESE YEARS."""

plt.figure(figsize=(16,6),dpi=100)
sns.barplot(A['Year'],A['Diphtheria '],palette='cubehelix')
plt.title('DIPTHERIA IMMUNIZATION COVERAGE',size=20)
plt.grid(color='grey',axis='y')
plt.tight_layout()

"""FROM ABOVE CORRELATION MATRIX WE CAN ALSO OBSERVE THAT THINNESS BETWEEN 1-19 YEARS AND THINNESS BETWEEN 1-5 YEARS ARE ALSO NEGATIVELY CORRELATED, SO LET'S SEE WHETHER THESE FEATURES HAVE INCREASED OR DECREASED."""

plt.figure(figsize=(16,6))
sns.barplot(A['Year'],A[' thinness  1-19 years'],color='orange')
plt.title('THINNESS BETWEEN 1-19 YEARS(YEAR WISE)',size=20)
plt.grid(color='grey',axis='y')
plt.tight_layout()

plt.figure(figsize=(16,6))
sns.barplot(A['Year'],A[' thinness 5-9 years'],color='blue')

plt.title('THINNESS BETWEEN 5-9 YEARS(YEAR WISE)',size=20)
plt.grid(color='grey',axis='y')
plt.tight_layout()

"""Since BMI(BODY MASS INDEX) is highly correlated(positively) with Life expectancy of people living in India, we will visualize the trend of this feature. """

#Visulaizing the trend of BMI

plt.figure(figsize=(16,6),dpi=100)
sns.barplot(A['Year'],A[' BMI '],palette='muted')
plt.grid(color='grey',axis='y')
plt.tight_layout()
plt.title('BODY MASS INDEX')

"""# NOW WE WILL SEE HOW SCHOOLING IMPACTS LIFESPAN OF HUMANS IN INDIA??"""

#plotting the line graph between No.Of schooling years and Life expectancy
plt.figure(figsize=(14,6),dpi=100)
plt.plot(A['Life expectancy '],A['Schooling'],marker='o')

plt.grid(color='grey')
plt.xlabel('LIFE EXPECTANCY')
plt.ylabel('NO. OF SCHOOLING YEARS')
plt.title('LINE GRAPH BETWEEN LIFE EXPECTANCY AND SCHOOLING')

plt.figure(figsize=(16,6),dpi=100)
sns.barplot(A['Year'],A['Schooling'],palette='coolwarm')
plt.grid(color='grey',axis='y')
plt.title('NO. OF SCHOOLING YEARS(YEAR WISE)',size=20)
plt.tight_layout()

"""LET'S SEE HOW GDP AND POPULATION OF OUR COUNTRY HAS INCREASED OR DECREASED IN THESE YEARS."""

#Visulaizing the GDP per capita of India between(2000-2013)
plt.figure(figsize=(16,6),dpi=100)
sns.barplot(A['Year'],A['GDP'],palette='cubehelix')
plt.grid(color='grey',axis='y')
plt.title('GDP PER CAPITA (YEAR WISE)',size=20)
plt.tight_layout()

plt.figure(figsize=(16,6),dpi=100)

sns.barplot(A['Year'],A['Population'],palette='icefire')
plt.title('POPULATION(YEAR WISE)',size=20)
plt.grid(color='grey',axis='y')
plt.tight_layout()

"""TOTAL EXPENDITURE MEANS GENERAL GOVERNMENT OF INDIA EXPENDITURE ON HEALTH AS A PERCENTAGE OF TOTAL GOVERNMENT EXPENDITURE."""

plt.figure(figsize=(16,6),dpi=100)
plt.plot(A['Year'],A['Total expenditure'],color='green',marker='o')
plt.grid(color='grey',axis='y')
plt.xlabel('YEARS')
plt.ylabel('TOTAL EXPENDITURE ON HEALTH')
plt.tight_layout()

v1=A['Life expectancy '].mean()
v2=A['Adult Mortality'].mean()
v3=A['infant deaths'].mean()
print('AVERAGE LIFE EXPECATNCY OF INDIA:',v1)
print('AVERAGE ADULT MORTALITY RATE IN INDIA:',v2)
print('AVERAGE INFANT DEATHS HAPPENING IN INDIA PER 1000 POPULATION:',v3)

"""#CONCLUSION

From this dataset(LIFE EXPECTANCY) provided by WHO(source: Kaggle) we tried to draw some useful insights that how life expecatncy in India is affected with the factors like adult mortality,infant deaths, polio,hepatitis b,diptheria immunization coverage and many others. We also tried to observe that how Schooling affects the Lifespan of Humans in India and how GDP(GROSS DOMESTIC PRODUCT) per capita is increased or decreased in India, we also visualized the trend of population in India in these years.

**COLUMNS:**
"""

#Country: Country
#Year: Year
#Status: Developed or Developing status
#Life expectancy: Life Expectancy in age
#Adult Mortality: Adult Mortality Rates of both sexes (probability of dying between 15 and 60 years per 1000 population)
#infant deaths: Number of Infant Deaths per 1000 population
#Alcohol: Alcohol, recorded per capita (15+) consumption (in litres of pure alcohol)
#percentage expenditure: Expenditure on health as a percentage of Gross Domestic Product per capita(%)
#Hepatitis B: Hepatitis B (HepB) immunization coverage among 1-year-olds (%)
#Measles: Measles - number of reported cases per 1000 population
#BMI: Average Body Mass Index of entire population
#under-five deaths: Number of under-five deaths per 1000 population
#PolioPolio (Pol3) immunization coverage among 1-year-olds (%)
#Total expenditure: General government expenditure on health as a percentage of total government expenditure (%)
#Diphtheria: Diphtheria tetanus toxoid and pertussis (DTP3) immunization coverage among 1-year-olds (%)
#HIV/AIDS: Deaths per 1 000 live births HIV/AIDS (0-4 years)
#GDP: Gross Domestic Product per capita (in USD)
#Population: Population of the country
#thinness 1-19 years: Prevalence of thinness among children and adolescents for Age 10 to 19 (% )
#thinness 5-9 years: Prevalence of thinness among children for Age 5 to 9(%)
#Income composition of resources: Human Development Index in terms of income composition of resources (index ranging from 0 to 1)
#Schooling: Number of years of Schooling(years)